flowchart TB
    
    Vehicle -- Initial --> Location
    Vehicle -- Current --> Location
    Demand -- Pickup --> Location
    Demand -- Dropoff --> Location
    Demand -- Current --> Location
    Demand -- Current --> Vehicle
    Location -- Segment --> Segment
    Segment -- Source --> Intersection
    Segment -- Target --> Intersection

    ChargingStation -- Current --> Vehicle
    ChargingStation -- Location --> Location