image: maven:3.6.3-jdk-14

variables:
  MAVEN_CLI_OPTS: '-s settings.xml --batch-mode'
  MAVEN_OPTS: '-Dmaven.repo.local=.m2/repository'

cache:
  paths:
    - .m2/repository

stages:
  - lint
  - compile
  - test
  - package
  - deploy

lint:
  stage: lint
  script:
    - mvn $MAVEN_CLI_OPTS checkstyle:check
  artifacts:
    paths:
      - '*/target'

compile:
  stage: compile
  script:
    - mvn $MAVEN_CLI_OPTS compile
  artifacts:
    paths:
      - '*/target'

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    paths:
      - '*/target'

package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - '*/target'

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  artifacts:
    paths:
      - '*/target'
