image: maven:3.6.3-jdk-14

variables:
  MAVEN_CLI_OPTS: '-s settings.xml --batch-mode'
  MAVEN_OPTS: '-Dmaven.repo.local=.m2/repository'

cache:
  paths:
    - .m2/repository
    - '*/target'

stages:
  - lint
  - compile
  - test
  - package
  - deploy

lint:
  stage: lint
  script:
    - mvn $MAVEN_CLI_OPTS checkstyle:check

compile:
  stage: compile
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
