classDiagram
    direction LR
    
    class Statistics {
        RecordCrossing(Vehicle v, Segment p, Segment n, Double t)
        RecordPickupDecline(Vehicle v, Demand d, Double t)
        RecordPickupAccept(Vehicle v, Demand d, Double t)
        RecordDropoff(Vehicle v, Demand d, Double t)
        RecordSpeed(Vehicle v, Double s, Double t)
        RecordDistance(Vehicle v, Double d, Double t)
        RecordStep(Double s, Double t)
    }