flowchart TB
    
    model
    parser
    controller
    simulator
    statistics
    viewer
    program
    exporter

    parser --> model
    controller --> model
    statistics --> model
    viewer --> simulator
    simulator --> controller
    simulator --> statistics
    program --> parser
    program --> viewer
    program --> exporter
    exporter --> statistics